name: CI

env:
  ACTIONS_STEP_DEBUG: true

on:
  push:
    branches:
      - main
  pull_request:
    types: ['opened', 'reopened', 'synchronize']

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        node: ['18', '20']

    if: ${{ !contains(github.event.head_commit.message, '[skip-test]') }}

    runs-on: ubuntu-latest
    name: Node ${{ matrix.node }} build

    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.15.3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --loglevel=debug

      - run: pnpm run format:check
      - run: pnpm run lint
      - run: pnpm run type-check
      - run: pnpm run test
      - run: pnpm run build
